### ISSUE TITLE
Cannot buid sketches for empty set

### ISSUE THREAD

**Issue by chongdae** [apache/datasketches-postgresql#35]
theta_sketch_union does not treat `null` as empty set. https://github.com/apache/datasketches-postgresql/issues/27

```
select theta_sketch_get_estimate(theta_sketch_union(theta_sketch_build(1), theta_sketch_build(2)));

select theta_sketch_get_estimate(theta_sketch_union(theta_sketch_build(1), null));

```

First query returns "2", but second one returns "NULL".

How can I build empty set sketches?

**Comment by chongdae** [comment]
In datasketches-hive, null is treated as empty set.

https://github.com/apache/datasketches-hive/blob/master/src/main/java/org/apache/datasketches/hive/theta/UnionSketchUDF.java

In this case, `theta_sketch_union(null, null)` returns empty sketch, not `null`.

**Comment by AlexanderSaydakov** [comment]
This is because theta_sketch_union function is declared "strict" in datasketches_theta_sketch.sql
I will fix this.

**Comment by chongdae** [comment]
FYI. To build empty sketch, `theta_sketch_a_not_b(theta_sketch_build(1), theta_sketch_build(1))` works.

@AlexanderSaydakov Could you add simpler solution? For example `theta_sketch_build()` without any argument returns empty sketches. (Or you can introduce other function.)

It can be helpful. In SQL, we can easily manipulate as `coallesce(sketches_may_be_null, theta_sketch_build())`.

**Comment by AlexanderSaydakov** [comment]
Why would you need an empty sketch having this fix?
