### ISSUE TITLE
About Aod_sketch performance

### ISSUE THREAD

**Issue by developerwxl** [apache/datasketches-postgresql#46]
Hi~
  I want to use aod_sketch in our company project. But i meet performance issues that use aod_sketch.
  I run this query in the PostgreSQL with version postgresql10-10.9-1PGDG.rhel7.x86_64.rpm. And the machine is AWS ec2, Redhat, C5.9Xlarge ( 36 vCPUs, 72G memory).
And the data size is very small.
  Data size: Just one 4k sketch data intersection one 4K sketch data. But the SQL runs for almost 10 seconds.
  Are there any performance know issues  ? Or other parameters that can improve the performance. Did you meet the same problem?
   SQL like this:
```
with
a as(select sk from test_ds_sketch where id ='3113'),   # just one record
b as ( select sk from  test_ds_sketch where id='2662')  # just one record
,
c as (select 171213 as network_id,aod_sketch_get_estimate(aod_sketch_intersection(a.sk,b.sk))/aod_sketch_get_estimate(a.sk)
as ratio from  a,b),
select * from c
```

**Comment by AlexanderSaydakov** [comment]
I don't have an answer, but a few suggestions:
- Try simplifying the query to identify which part of it leads to this poor performance
- Try the same thing with theta sketch. This particular query does not use the payload (array of doubles).
- Try a newer version of PostgreSQL (why version 10? the current one is 14)

**Comment by developerwxl** [comment]
Thank you for your response.
I will try your suggestions. I'm going to try it. Then send you a response.

**Comment by developerwxl** [comment]
Thank you for your response.
I'm going to try it. Then send you a response.

**Comment by AlexanderSaydakov** [comment]
@developerwxl did you have a chance to gather some more information about this?
