### ISSUE TITLE
Make aggregations parallel SAFE

### ISSUE THREAD

**Issue by andyndang** [apache/datasketches-postgresql#61]
In order for postgres to execute parallel execution plan, the aggregation function needs to be marked as SAFE.

Reading this documentation it requires the function to specify a combiner:
https://www.postgresql.org/docs/current/sql-createaggregate.html#:~:text=An%20aggregate%20can%20optionally%20support%20partial,PARALLEL%20SAFE%20to%20enable%20parallel%20aggregation.

Would be nice if this extension can support that!

**Comment by AlexanderSaydakov** [comment]
I will look into this.

**Comment by AlexanderSaydakov** [comment]
fixed by #63

**Comment by AlexanderSaydakov** [comment]
@andyndang The change is in the master. Would you be willing to try this before the next release?

**Comment by AlexanderSaydakov** [comment]
@andyndang 1.6.0-rc1 release candidate is out there. The vote is open. You are welcome to participate.

**Comment by AlexanderSaydakov** [comment]
1.6.0 has been released

**Comment by jmalkin** [comment]
Full release notes are available here: [https://github.com/apache/datasketches-postgresql/releases/tag/1.6.0](https://github.com/apache/datasketches-postgresql/releases/tag/1.6.0)
